const projectData = [
  {
    title: "Raycast Vehicle Engine",
    miniDesc:
      "Simply upload your favourite car's chassis model and car's wheel model and the RV Engine would automatically create a car with the same look and feel. It would also be able to control the car's movement and rotation...",
    website: "https://rv-engine.vercel.app/",
    github: "https://github.com/Jaagrav/raycast-vehicle-engine",
    img: "/assets/images/projects/Rv-Engine.png",
    link: "raycast-vehicle-engine",
    showOnHome: true,
    tech: [
      "ThreeJS",
      "CannonJS",
      "Stats.js",
      "JSZip",
      "Babel",
      "Guify",
      "File-saver",
      "Three-gltf-exporter",
      "Webpack",
    ],
    desc: "Simply upload your favourite car's chassis model and car's wheel model and the RV Engine would automatically create a car with the same look and feel. It would also be able to control the car's movement and rotation. Add physics and everything else you want to the car and you're good to go. After that you can simply download it as a zip file. Follow the same setup procedure, and you have a new raycast vehicle generated.",
  },
  {
    title: "Ayasya Eco",
    miniDesc:
      "Ayasya is a building material manufacturing company founded to address the problem of plastics by manufacturing affordable and sustainable building materials. The company is...",
    website: "https://ayasyaeco.com/",
    github: null,
    img: "/assets/images/projects/Ayasya.png",
    link: "ayasya-eco",
    showOnHome: true,
    tech: [
      "NextJS",
      "TailwindCSS",
      "Axios",
      "Firebase",
      "React",
      "React-Multi-Carousel",
      "SendGrid",
      "Next-Page-Transitions",
    ],
    desc: "Ayasya is a building material manufacturing company founded to address the problem of plastics by manufacturing affordable and sustainable building materials. The company is currently working on products which are plastic stuff made from recycled plastic. ",
  },
  {
    title: "Brisko",
    miniDesc:
      "So this website was developed for a client. Wonder who the client is? It’s Saloni Garg and Amit Sagtani. It was a fun little project, developed using Next, Tailwind and lots...",
    website: "https://brisko.app/",
    github: null,
    img: "/assets/images/projects/Brisko.png",
    link: "brisko",
    showOnHome: false,
    tech: [
      "NextJS",
      "TailwindCSS",
      "React",
      "Google-Sheets-API",
      "SendGrid",
      "Axios",
      "React-vertical-timeline-component",
      "React-swipeable-views",
      "SweetAlert2",
    ],
    desc: "Experience the new web3 social media, watch the new-age content and earn crypto rewards! So this website was developed for a client. Wonder who the client is? It’s Saloni Garg and Amit Sagtani. It was a fun little project, developed using Next, Tailwind and lots and lots of hatred! I am kidding about the last part, go check it out!",
  },
  {
    title: "CodeX",
    miniDesc:
      "My most popular project on Github, CodeX is an online compiler for various languages like Java, C++, Python, etc. Execute code in various...",
    website: "https://codexweb.netlify.app/",
    github: "https://github.com/Jaagrav/CodeX",
    img: "/assets/images/projects/Codex.png",
    link: "codex",
    showOnHome: false,
    tech: [
      "React",
      "MaterialUI",
      "Axios",
      "Firebase",
      "Netlify-CLI",
      "Netlify-Lambda",
      "React-Ace",
    ],
    desc: "100+ stars on Github, my most popular project on Github, CodeX is an online compiler for various languages like Java, C++, Python, etc. Execute code in various languages on your own website for free with the CodeX API!!!",
  },
  {
    title: "Xper",
    miniDesc:
      "Xper is a realtime code editor where you can both write and save your code in realtime! The unique thing about Xper is it updates your deployed code in realtime, which means you can...",
    website: "https://xperbycoder.netlify.app/",
    github: "https://github.com/Jaagrav/Xper",
    img: "/assets/images/projects/Xper.png",
    link: "xper",
    showOnHome: false,
    tech: [
      "React",
      "MaterialUI",
      "Axios",
      "Firebase",
      "SweetAlert2",
      "React-Ace",
    ],
    desc: "Xper is a realtime code editor where you can both write and save your code in realtime! The unique thing about Xper is it updates your deployed code in realtime, which means you can code on your computer and immediately be able to check how it looks like on your phone, tablet, and literally everywhere else. Xper is developed in React, which makes it a lightning fast code editor considering everything is being saved remotely.",
  },
  {
    title: "Fragments",
    miniDesc:
      "Fragments is a light weight code editor which supports multiple languages, store your code/snippets here for future use. In Fragments, you can create/edit/store code and snippets for future use...",
    website: "https://fragmentsbycoder.netlify.app/",
    github: "https://github.com/Jaagrav/Fragments",
    img: "/assets/images/projects/Fragments.png",
    link: "fragments",
    showOnHome: false,
    tech: ["AceJS", "jQuery", "Font-Awesome", "HTML", "CSS", "JavaScript"],
    desc: "Fragments is a prototype of Xper 2.0 which will allow you to code, execute and view them in RealTime on all platforms that you visit your website from. However in Fragments, you can create/edit/store code and snippets for future use. Fragments would soon become a text editor for PC and Mac after I implement electronjs into this project.",
  },
];

export default projectData;
